const puppeteer = require('puppeteer');

(async () => {
  console.log('🚀 Starting Automated Features Test...');
  
  // Launch the browser
  const browser = await puppeteer.launch({ 
    headless: false,
    defaultViewport: null,
    args: ['--start-maximized']
  });
  
  const page = await browser.newPage();
  
  try {
    console.log('🌐 Navigating to Vercel deployment login page...');
    await page.goto('https://updates-aotms-mcvw.vercel.app/#/login', { waitUntil: 'domcontentloaded', timeout: 60000 });
    
    // Wait for the login form to be visible
    await page.waitForSelector('#loginForm', { visible: true });
    
    console.log('⌨️  Entering credentials...');
    // Type in email and password
    await page.type('#loginEmail', 'ramanadhamjayaveer@gmail.com', { delay: 50 });
    await page.type('#loginPassword', 'Jayaveer!@#1837', { delay: 50 });
    
    console.log('🖱️  Clicking Sign In...');
    await page.click('#loginForm button[type="submit"]');
    
    console.log('⏳ Waiting for Dashboard to load...');
    await page.waitForSelector('.sidebar-nav', { visible: true, timeout: 10000 });
    console.log('✅ Login Successful!');

    // Wait a brief moment to ensure full render
    await new Promise(r => setTimeout(r, 2000));

    console.log('🔄 Navigating to Features page...');
    // Look for the "Features" sidebar link and click it
    try {
      await page.waitForSelector('a[href="#/work/features"]', { timeout: 5000 });
      await page.click('a[href="#/work/features"]');
    } catch (e) {
      // Fallback navigation
      console.log('⚠️ Could not click sidebar link, using direct navigation...');
      await page.goto('https://updates-aotms-mcvw.vercel.app/#/work/features');
    }

    // Wait for the Add Feature button to appear on the Features page
    await page.waitForSelector('#addFeatureBtn', { visible: true, timeout: 10000 });
    console.log('✅ Features page loaded!');

    console.log('🖱️  Clicking + New Feature...');
    await page.click('#addFeatureBtn');

    // Wait for the modal to open
    await page.waitForSelector('#featureModal', { visible: true });
    await page.waitForSelector('#featureTitle', { visible: true });
    
    console.log('⌨️  Filling out random Feature data...');
    
    const randomId = Math.floor(Math.random() * 10000);
    const featureTitle = `Random Automated System Feature #${randomId}`;
    
    // Type in Title
    await page.type('#featureTitle', featureTitle, { delay: 50 });
    
    // Select Status (Randomize between PLANNED, IN_PROGRESS, COMPLETED)
    const statuses = ['PLANNED', 'IN_PROGRESS', 'COMPLETED'];
    const randomStatus = statuses[Math.floor(Math.random() * statuses.length)];
    await page.select('#featureStatus', randomStatus);

    // Type in Description
    await page.type('#featureDesc', `This is an automated feature testing note generated by Puppeteer.`, { delay: 30 });
    
    console.log('🖱️  Saving Feature...');
    // Submit the form
    await page.click('#featureForm button[type="submit"]');

    // Wait for the modal to close
    console.log('⏳ Waiting for modal to close and data to refresh...');
    await page.waitForSelector('#featureModal', { hidden: true, timeout: 10000 });
    
    // Wait a couple seconds for the API fetch and render to complete
    await new Promise(r => setTimeout(r, 3000));

    console.log('✅ Feature Successfully Added!');
    
    // Take a screenshot of the successful feature creation
    console.log('📸 Taking a screenshot of the Features page...');
    await page.screenshot({ path: 'features-success-screenshot.png' });
    console.log('💾 Screenshot saved as features-success-screenshot.png');
    
  } catch (error) {
    console.error('❌ Test Failed:', error.message);
    try {
      await page.screenshot({ path: 'features-error-screenshot.png' });
      console.log('📸 Saved error screenshot as features-error-screenshot.png');
    } catch (e) {}
  } finally {
    console.log('Closing browser in 5 seconds...');
    await new Promise(r => setTimeout(r, 5000));
    await browser.close();
    console.log('🏁 Test completed.');
  }
})();
