const puppeteer = require('puppeteer');

(async () => {
  console.log('🚀 Starting Automated Todo Test...');
  
  // Launch the browser
  const browser = await puppeteer.launch({ 
    headless: false,
    defaultViewport: null,
    args: ['--start-maximized']
  });
  
  const page = await browser.newPage();
  
  try {
    console.log('🌐 Navigating to Vercel deployment login page...');
    await page.goto('https://updates-aotms-mcvw.vercel.app/#/login', { waitUntil: 'domcontentloaded', timeout: 60000 });
    
    // Wait for the login form to be visible
    await page.waitForSelector('#loginForm', { visible: true });
    
    console.log('⌨️  Entering credentials...');
    // Type in email and password
    await page.type('#loginEmail', 'ramanadhamjayaveer@gmail.com', { delay: 50 });
    await page.type('#loginPassword', 'Jayaveer!@#1837', { delay: 50 });
    
    console.log('🖱️  Clicking Sign In...');
    await page.click('#loginForm button[type="submit"]');
    
    console.log('⏳ Waiting for Dashboard to load...');
    await page.waitForSelector('.sidebar-nav', { visible: true, timeout: 10000 });
    console.log('✅ Login Successful!');

    // Wait a brief moment to ensure full render
    await new Promise(r => setTimeout(r, 2000));

    console.log('🔄 Navigating to TODO page...');
    // Look for the "TODO" sidebar link and click it
    try {
      await page.waitForSelector('a[href="#/work/todo"]', { timeout: 5000 });
      await page.click('a[href="#/work/todo"]');
    } catch (e) {
      // Fallback navigation
      console.log('⚠️ Could not click sidebar link, using direct navigation...');
      await page.goto('https://updates-aotms-mcvw.vercel.app/#/work/todo');
    }

    // Wait for the Add Todo button to appear on the Todo page
    await page.waitForSelector('#addTodoBtn', { visible: true, timeout: 10000 });
    console.log('✅ TODO page loaded!');

    console.log('🖱️  Clicking + Add Todo...');
    await page.click('#addTodoBtn');

    // Wait for the modal to open
    await page.waitForSelector('#todoModal', { visible: true });
    await page.waitForSelector('#todoTitle', { visible: true });
    
    console.log('⌨️  Filling out random Todo data...');
    
    const randomId = Math.floor(Math.random() * 10000);
    const todoTitle = `Random Automated Todo #${randomId}`;
    
    // Type in Title
    await page.type('#todoTitle', todoTitle, { delay: 50 });
    
    // Select Type (Randomize between PERSONAL, TEAM)
    const types = ['PERSONAL', 'TEAM'];
    const randomType = types[Math.floor(Math.random() * types.length)];
    await page.select('#todoType', randomType);

    // Select Priority (Randomize between LOW, MEDIUM, HIGH, URGENT)
    const priorities = ['LOW', 'MEDIUM', 'HIGH', 'URGENT'];
    const randomPriority = priorities[Math.floor(Math.random() * priorities.length)];
    await page.select('#todoPriority', randomPriority);

    // Select Status (Randomize)
    const statuses = ['TODO', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'];
    const randomStatus = statuses[Math.floor(Math.random() * statuses.length)];
    await page.select('#todoStatus', randomStatus);

    // Type in Description
    await page.type('#todoDesc', `This is an automated TODO testing note generated by Puppeteer.`, { delay: 30 });
    
    console.log('🖱️  Saving Todo...');
    // Submit the form
    await page.click('#todoForm button[type="submit"]');

    // Wait for the modal to close
    console.log('⏳ Waiting for modal to close and data to refresh...');
    await page.waitForSelector('#todoModal', { hidden: true, timeout: 10000 });
    
    // Wait a couple seconds for the API fetch and render to complete
    await new Promise(r => setTimeout(r, 3000));

    console.log('✅ Todo Successfully Added!');
    
    // Take a screenshot of the successful todo creation
    console.log('📸 Taking a screenshot of the TODO page...');
    await page.screenshot({ path: 'todo-success-screenshot.png' });
    console.log('💾 Screenshot saved as todo-success-screenshot.png');
    
  } catch (error) {
    console.error('❌ Test Failed:', error.message);
    try {
      await page.screenshot({ path: 'todo-error-screenshot.png' });
      console.log('📸 Saved error screenshot as todo-error-screenshot.png');
    } catch (e) {}
  } finally {
    console.log('Closing browser in 5 seconds...');
    await new Promise(r => setTimeout(r, 5000));
    await browser.close();
    console.log('🏁 Test completed.');
  }
})();
