const puppeteer = require('puppeteer');

(async () => {
  console.log('🚀 Starting Automated WorkToday Test...');

  // Launch the browser
  const browser = await puppeteer.launch({
    headless: false,
    defaultViewport: null,
    args: ['--start-maximized']
  });

  const page = await browser.newPage();

  try {
    console.log('🌐 Navigating to Vercel deployment login page...');
    await page.goto('https://updates-aotms-mcvw.vercel.app/#/login', { waitUntil: 'domcontentloaded', timeout: 60000 });

    // Wait for the login form to be visible
    await page.waitForSelector('#loginForm', { visible: true });

    console.log('⌨️  Entering credentials...');
    // Type in email and password
    await page.type('#loginEmail', 'ramanadhamjayaveer@gmail.com', { delay: 50 });
    await page.type('#loginPassword', 'Jayaveer!@#1837', { delay: 50 });

    console.log('🖱️  Clicking Sign In...');
    await page.click('#loginForm button[type="submit"]');

    console.log('⏳ Waiting for Dashboard to load...');
    await page.waitForSelector('.sidebar-nav', { visible: true, timeout: 10000 });
    console.log('✅ Login Successful!');

    // Wait a brief moment to ensure full render
    await new Promise(r => setTimeout(r, 2000));

    console.log('🔄 Navigating to Today\'s Work...');
    // Look for the "Today's Work" sidebar link and click it
    try {
      await page.waitForSelector('a[href="#/work/today"]', { timeout: 5000 });
      await page.click('a[href="#/work/today"]');
    } catch (e) {
      // Fallback navigation
      console.log('⚠️ Could not click sidebar link, using direct navigation...');
      await page.goto('https://updates-aotms-mcvw.vercel.app/#/work/today');
    }

    // Wait for the Add Execution button to appear on the WorkToday page
    await page.waitForSelector('#addExecutionBtn', { visible: true, timeout: 10000 });
    console.log('✅ Today\'s Work page loaded!');

    console.log('🖱️  Clicking + Add Execution Point...');
    await page.click('#addExecutionBtn');

    // Wait for the modal to open
    await page.waitForSelector('#executionModal', { visible: true });
    await page.waitForSelector('#execTitle', { visible: true });

    console.log('⌨️  Filling out random Execution Point data...');

    const randomId = Math.floor(Math.random() * 10000);
    const taskTitle = `Random Automated Task #${randomId}`;

    // Type in Title
    await page.type('#execTitle', taskTitle, { delay: 50 });

    // Select Priority (Randomize between LOW, MEDIUM, HIGH)
    const priorities = ['LOW', 'MEDIUM', 'HIGH'];
    const randomPriority = priorities[Math.floor(Math.random() * priorities.length)];
    await page.select('#execPriority', randomPriority);

    // Type in Update/Notes
    await page.type('#execUpdate', `This is an automated test note generated by Puppeteer for testing purposes.`, { delay: 30 });

    console.log('🖱️  Saving Execution Point...');
    // Submit the form
    await page.click('#executionForm button[type="submit"]');

    // Wait for the modal to close
    console.log('⏳ Waiting for modal to close and data to refresh...');
    await page.waitForSelector('#executionModal', { hidden: true, timeout: 10000 });

    // Wait a couple seconds for the API fetch and render to complete
    await new Promise(r => setTimeout(r, 3000));

    console.log('✅ Task Successfully Added!');

    // Take a screenshot of the successful registration
    console.log('📸 Taking a screenshot of the Today\'s Work page...');
    await page.screenshot({ path: 'worktoday-success-screenshot.png' });
    console.log('💾 Screenshot saved as worktoday-success-screenshot.png');

  } catch (error) {
    console.error('❌ Test Failed:', error.message);
    try {
      await page.screenshot({ path: 'worktoday-error-screenshot.png' });
      console.log('📸 Saved error screenshot as worktoday-error-screenshot.png');
    } catch (e) { }
  } finally {
    console.log('Closing browser in 5 seconds...');
    await new Promise(r => setTimeout(r, 5000));
    await browser.close();
    console.log('🏁 Test completed.');
  }
})();
